INSERT INTO QUESTIONS_LIST (QUESTIONS_UID, QUESTIONS, ORDERS)
VALUES ('Q1', "반려둥물에 관심이 있나요?", 1);

INSERT INTO QUESTIONS_LIST (QUESTIONS_UID, QUESTIONS, ORDERS)
VALUES ('Q2', "반려동물을 키울 생각이 있나요? ", 2);

INSERT INTO QUESTIONS_LIST (QUESTIONS_UID, QUESTIONS, ORDERS)
VALUES ('Q3', "유기동물을 입양할 생각이 있나요?", 3);

INSERT INTO QUESTIONS_LIST (QUESTIONS_UID, QUESTIONS, ORDERS)
VALUES ('Q4', "반려동물을 키울 환경이 준비되어 있나요?", 4);

INSERT INTO QUESTIONS_LIST (QUESTIONS_UID, QUESTIONS, ORDERS)
VALUES ('Q5', "반려동물이 삶의 만족도에 영향을 준다고 생각하시나요?", 5);

INSERT INTO EXAMPLE_LIST (EXAMPLE_UID, EXAMPLE, ORDERS)
VALUES ('E1', "매우 그렇다", 1); 

INSERT INTO EXAMPLE_LIST (EXAMPLE_UID, EXAMPLE, ORDERS)
VALUES ('E2', "그렇다", 2);

INSERT INTO EXAMPLE_LIST (EXAMPLE_UID, EXAMPLE, ORDERS)
VALUES ('E3', "그렇지 않다", 3);

INSERT INTO EXAMPLE_LIST (EXAMPLE_UID, EXAMPLE, ORDERS)
VALUES ('E4', "전혀 그렇지 않다", 4);


INSERT ANSWERS (QUESTIONS_UID, EXAMPLE_UID)
VALUES ('Q1', 'E1'),('Q1', 'E2'),('Q1', 'E3'),('Q1', 'E4'),
('Q2', 'E1'),('Q2', 'E2'),('Q2', 'E3'),('Q2', 'E4'),
('Q3', 'E1'),('Q3', 'E2'),('Q3', 'E3'),('Q3', 'E4'),
('Q4', 'E1'),('Q4', 'E2'),('Q4', 'E3'),('Q4', 'E4'),
('Q5', 'E1'),('Q5', 'E2'),('Q5', 'E3'),('Q5', 'E4')
;