
CREATE TABLE ANSWER
(
  ANSWER_UID  VARCHAR(200) NOT NULL COMMENT '문항대표값',
  ANSWER_LIST VARCHAR(200) NOT NULL COMMENT '문항답변',
  PRIMARY KEY (ANSWER_UID)
) COMMENT '문항답변';

CREATE TABLE QUESTION
(
  QUESTION_UID  VARCHAR(200) NOT NULL COMMENT '질문대표값',
  QUESTION_LIST VARCHAR(200) NOT NULL COMMENT '질문',
  PRIMARY KEY (QUESTION_UID)
) COMMENT '질문';

CREATE TABLE SURVEY
(
  QUESTION_UID VARCHAR(200) NOT NULL COMMENT '질문대표값',
  ANSWER_UID   VARCHAR(200) NOT NULL COMMENT '문항대표값'
) COMMENT '질문-문항';

CREATE TABLE SURVEYOR
(
  USER_ID    VARCHAR(200) NOT NULL COMMENT '사용자대표값',
  NAME       VARCHAR(200) NOT NULL COMMENT '이름',
  BIRTH_DATE VARCHAR(200) NOT NULL COMMENT '생년월일',
  PASSWORD   VARCHAR(200) NOT NULL COMMENT '비밀번호',
  PHONE      VARCHAR(200) NOT NULL COMMENT '전화번호',
  PRIMARY KEY (USER_ID)
) COMMENT '설문자';

CREATE TABLE USERS_ANSWER
(
  USER_ID      VARCHAR(200) NOT NULL COMMENT '사용자대표값',
  ANSWER_UID   VARCHAR(200) NOT NULL COMMENT '문항대표값',
  QUESTION_UID VARCHAR(200) NOT NULL COMMENT '질문대표값'
) COMMENT '사용자답변';

ALTER TABLE SURVEY
  ADD CONSTRAINT FK_ANSWER_TO_SURVEY
    FOREIGN KEY (ANSWER_UID)
    REFERENCES ANSWER (ANSWER_UID);

ALTER TABLE SURVEY
  ADD CONSTRAINT FK_QUESTION_TO_SURVEY
    FOREIGN KEY (QUESTION_UID)
    REFERENCES QUESTION (QUESTION_UID);

ALTER TABLE USERS_ANSWER
  ADD CONSTRAINT FK_SURVEYOR_TO_USERS_ANSWER
    FOREIGN KEY (USER_ID)
    REFERENCES SURVEYOR (USER_ID)
    ON DELETE CASCADE;

ALTER TABLE USERS_ANSWER
  ADD CONSTRAINT FK_ANSWER_TO_USERS_ANSWER
    FOREIGN KEY (ANSWER_UID)
    REFERENCES ANSWER (ANSWER_UID);

ALTER TABLE USERS_ANSWER
  ADD CONSTRAINT FK_QUESTION_TO_USERS_ANSWER
    FOREIGN KEY (QUESTION_UID)
    REFERENCES QUESTION (QUESTION_UID);
